FORMAT: 1A
HOST: http://161.35.135.236/v1

# VUTTR

## Data Structures

## User (object)
+ id: 1 (number)
+ name: Mateus Deitos (string)
+ email: mate.deitos@hotmail.com (string)
+ created_at: `2021-01-08T05:50:38.000Z` (string)
+ updated_at: `2021-01-08T05:50:38.000Z` (string)

## Tool (object)
+ id: 1 (number)
+ title: Notion (string)
+ description: All in one tool to organize teams and ideas. Write, plan, collaborate, and get organized. ✔ (string)
+ url: `https://notion.so` (string)
+ tags: `nice`, `notes` (array)
+ created_at: `2021-01-08T05:50:38.000Z` (string)
+ updated_at: `2021-01-08T05:50:38.000Z` (string)


# Group Users

## Cria novo usuário [POST /users]

+ Request (application/json)
    + Attributes (object)
        + name: Mateus Deitos (string)
        + email: mate.deitos@hotmail.com (string)
        + password: 123456 (string)
    

+ Response 201 (application/json)
    + Attributes (User)

# Group Sessions

## Realiza o Login [POST /sessions]

+ Request (application/json)
    + Attributes (object)
        + email: mate.deitos@hotmail.com (string)
        + password: 123456 (string)
    

+ Response 200 (application/json)
    + Attributes (object)
        + user (User)
        + token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTAzMjIzMjgsImV4cCI6MTYxMjkxNDMyOCwic3ViIjoiMSJ9.LIOB042_MukwN9wVCy_ODB9Dhd34z2CDcZNcdjmaeoU (string)

# Group Tools [/tools]

## Cria uma ferramenta [POST]

+ Request (application/json)
    + Attributes (object)
        + title: Notion (string)
        + description: All in one tool to organize teams and ideas. Write, plan, collaborate, and get organized. ✔ (string)
        + url: `https://notion.so` (string)
        + tags: `nice,top` (array)
    

+ Response 201 (application/json)
    + Attributes (Tool)

## Deleta uma ferramenta [DELETE /tools/{id}]
+ Parameters
    + id: 1 (number) - ID da ferramenta
    

+ Response 204

## Lista ferramentas [GET /tools{?tags}{?orderBy}{?limit}{?offset}]

+ Parameters
    + tags: node,http2,organizing (string, optional) - Tags da pesquisa separadas por vírgula
    + orderBy: `(title,ASC);(id,DESC)` (string, optional) - Ordenação dos resultados
        + Default: `(created_at, DESC)`
    + limit: 10 (number, optional) - Limite de resultados por página
        + Default: 10
    + offset: 10 (number, optional) - Posição dos resultados a serem retornados
        + Default: 0

+ Response 200 (application/json)
    + Attributes (object)
        + results (array[Tool])
        + currentOffset: 0 (number)
        + totalResults: 1 (number)