name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4 
        with:
          node-version: 14.x
    
      # Instalar dependências
      - name: Install Dependencies
        run: yarn
        
      # Executar build
      - name: Run build
        run: yarn build
        
      # Copiar todas as pastas para a Digital Ocean
      - name: Copy files to Digital Ocean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: ".,!node_modules"
          target: "app/bossabox-api-desafio/"
      # Acessar o servidor na Digital Ocean
      # Substituir o código na pasta dist pelo novo código
      # Instalar dependências na Digital Ocean
      # Executar testes unitários
      # Executar migrations 
      # Reiniciar pm2
      
